version: 2
updates:
- package-ecosystem: npm
  directory: "/website"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-hook-form
    versions:
    - 7.0.0
    - 7.0.5
    - 7.3.3
  - dependency-name: "@types/node"
    versions:
    - 14.14.41
  - dependency-name: "@material-ui/core"
    versions:
    - 5.0.0-alpha.28
    - 5.0.0-alpha.29
    - 5.0.0-alpha.31
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: node-sass
    versions:
    - 5.0.0
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
- package-ecosystem: npm
  directory: "/next"
  schedule:
    interval: daily
    time: "04:00"